apiVersion: v1
kind: ResourceQuoata
metadata:
    name: compute-quota
    namespace: dev
spec:
  hard:
    podas: "10"
    requests.cpu: "4"
    requests.memory: 5Gi
    limits.cpu: "10"
    limits.memory: 10Gi